import { ContainerPolitics, PoliticsTitle, PoliticsText, PoliticsSubTitle, PoliticsLink } from './styles'

const Politics = () => {
  return (
    <ContainerPolitics>
      <PoliticsTitle>políticas de privacidad</PoliticsTitle>
      <PoliticsText>Lo siguiente, es un documento legal que explica como cuidamos tus datos y los términos de uso del Servicio cuando utilizas nuestra plataforma. Gracias por tu confianza en nuestros <PoliticsLink href="">cursos virtuales</PoliticsLink> brindados a través de esta plataforma.</PoliticsText>
      <PoliticsSubTitle>Preliminar</PoliticsSubTitle>
      <PoliticsText>Escuela Americana de Innovación S.A.C. les da la bienvenida, Escuela Americana de Innovación S.A.C. de ahora en adelante será denominado como: “El Servicio” o el “Website”. En respeto a su privacidad le haremos saber qué información brindada utilizamos y que es lo que hacemos con dicha información. La siguiente Política de Privacidad fue creada para ayudarlo a entender cómo será usada la información que usted provee a Escuela Americana de Innovación S.A.C.. Esta Política de Privacidad aplica para toda la información que recolectamos sobre usted.</PoliticsText>
      <PoliticsSubTitle>Información que recolectamos</PoliticsSubTitle>
      <PoliticsText>Información de Registro. No se requiere que usted nos dé a nosotros ningún tipo de información personal para acceder a nuestro Website ni para ver la información que proveemos generalmente en nuestro Website. Sin embargo, podremos ofrecerle la oportunidad de registrarse con nosotros o unirse a nuestra lista de correo. A pesar de que no es necesario registrarse para acceder a nuestra Website, sí es necesario conectar cuentas de redes sociales para participar en los chats. En otros momentos, puede que también se le pida que nos provea información adicional, como su edad, género, y otra información personal para que usted reciba información adicional de nuestros servicios a futuro.</PoliticsText>
      <PoliticsText>Escuela Americana de Innovación S.A.C. podría necesitar esta información para conocerlo mejor, ayudarlo a entender nuevos servicios, programas y ofertas en las cuales usted pueda estar interesado y así mejorar su experiencia online.</PoliticsText>
      <PoliticsText>Recolección Automática de Datos. Usted podrá visitar nuestra Website y usar ciertos de nuestros servicios de manera anónima. No obstante, aunque se haya registrado con nosotros o no, Escuela Americana de Innovación S.A.C. puede recolectar cierta información personal para el uso de nuestros servicios. Por ejemplo, Escuela Americana de Innovación S.A.C. puede recolectar información concerniente al tipo de Navegador de Internet que usted usa, el tipo de computadora o sistema operativo que usted usa, su dirección de IP, la velocidad de su conexión, el nombre del dominio de su proveedor de servicio Internet, la localidad geográfica de dónde usted está accediendo a nuestros servicios y/o la Website o propaganda de donde usted se conectó a nuestro Website. Una vez que se haya registrado con nosotros, también rastreamos y recolectamos información sobre usted incluyendo sus transacciones con nosotros y los patrones que siguió usted al usar nuestra Website, como las páginas de la Website que usted visitó, búsquedas que condujo, y el tiempo que usted estuvo en nuestra Website. Si decide contactarnos, podremos guardar un historial de su correspondencia.</PoliticsText>
      <PoliticsText>Cookies. Cuando usted visita nuestra Website o pulsa cualquier hipervínculo que aparece en ella, o usa uno o más de nuestros servicios, podremos usar una tecnología industrial llamada “cookies” la cual almacena cierta información en su computadora y que nos permitirá personalizar su experiencia para alinearla con sus intereses y preferencias o simplemente facilitar su acceso al usar nuestros servicios. La mayoría de los Navegadores permitirán que usted elimine o bloquee las “cookies” de su computador o su disco duro o alertará las mismas cuando estas se activen. Por favor refiérase a las instrucciones de su Navegador para ayuda o para conocer mejor sus funciones. Por favor note, sin embargo, que si usted bloquea de su Navegador el uso de estos cookies, el servicio no podrá ser utilizado o no podrá acceder a nuestra Website o quizás pueda afectar el funcionamiento de la página como tal.</PoliticsText>
      <PoliticsSubTitle>Lo que hacemos con su información</PoliticsSubTitle>
      <PoliticsText>En general, Escuela Americana de Innovación S.A.C. podrá usar su información para proporcionar y mejorar El Servicio. Escuela Americana de Innovación S.A.C. podrá compartir esta información con los proveedores del servicio sobre contenido y otras entidades de forma no-personal para estudios demográficos e información preferencial para los usuarios del servicio o para otros propósitos. Esta información podrá incluir el uso y la data demográfica, pero no incluirá información personal (tal como su dirección de correo electrónico).</PoliticsText>
      <PoliticsText>Escuela Americana de Innovación S.A.C. no revelará, compartirá, venderá ni rentará información personal recolectada en nuestra Website a terceros para su uso promocional sin su consentimiento a menos que sea para un programa específico al que le podrá pedirnos no participar. Cualquier uso de esa información de parte de Escuela Americana de Innovación S.A.C. estará sujeto a esta Política de Privacidad. Nosotros no compartimos la información de sus cuentas de tarjetas de crédito con redes afiliadas ni ningún otro tercero, excepto al servicio de procesamiento de tarjetas de crédito descritos abajo. Para mantenerlo informado sobre nuestros servicios, podríamos enviar correos electrónicos y anuncios que son necesarios para la administración de nuestro Website y El Servicio. También podríamos proveer a nuestros usuarios con la opción de unirse a nuestra lista de correos electrónicos para recibir información adicional sobre nuestra Website, servicios y ofertas.</PoliticsText>
      <PoliticsSubTitle>Seguridad</PoliticsSubTitle>
      <PoliticsText>Usamos métodos razonables de seguridad para proteger la data que reside en nuestros servidores. Sin embargo, ningún sistema de seguridad es impenetrable, debido a esto, no le podemos garantizar la seguridad de nuestros servidores. Es también posible que la información que usted nos provea pueda ser interceptada durante la transmisión de datos.</PoliticsText>
      <PoliticsText>Cada vez que usted le brinde a Escuela Americana de Innovación S.A.C. información sensible (ejemplo: contraseñas, números de tarjeta de crédito, etc), Escuela Americana de Innovación S.A.C. tomara medidas comerciales razonables para proteger dicha información y establecer una conexión segura con nuestro Navegador de Web. Escuela Americana de Innovación S.A.C. emplea una tecnología industrial estándar conocida como secure-socket-layer (“SSL”) para proteger la transmisión de información de pago al Website. Puede usted chequear la seguridad de su conexión tras observar la barra de direcciones en su ventana de Navegador. Cuando usted acceda un servidor protegido por SSL, los primeros caracteres de la dirección cambiaran de “http” a “https."</PoliticsText>
      <PoliticsText>La Política de Privacidad de Escuela Americana de Innovación S.A.C. no se extiende a nada inherente en la operación de Internet, por lo tanto más lejos del control de Escuela Americana de Innovación S.A.C. y no se aplicará de ninguna manera contraria a la ley o los reglamentos del gobierno.</PoliticsText>
      <PoliticsSubTitle>Protección al menor</PoliticsSubTitle>
      <PoliticsText>En cumplimiento del Acta Federal de 1998 para la Privacidad On-line y la Protección de Niños (COPPA), no pediremos conscientemente información personal de ninguna persona menor a trece (13) años sin el consentimiento de sus padres. Cualquier persona que nos proporciona este tipo de información representa que tiene 13 o más años de edad</PoliticsText>
      <PoliticsSubTitle>Enlaces a otras redes</PoliticsSubTitle>
      <PoliticsText>Los enlaces a otras redes son una parte integral de la funcionalidad de Internet, incluyendo nuestra WebSite. Cualquier hipervínculo que disponga de una URL de un dominio distinto a Escuela Americana de Innovación S.A.C. en la barra de direcciones de su Navegador es un hipervínculo a una página fuera de nuestro servicio. Estas otras redes podrán enviar sus “cookies” a usted, recolectar data o solicitar información personal. Escuela Americana de Innovación S.A.C. no puede garantizar y no se hace responsable por el contenido de otras redes o páginas.</PoliticsText>
      <PoliticsText>Escuela Americana de Innovación S.A.C. no garantizará la seguridad ni la privacidad de ninguna información que usted revele a otros Websites, y usted lo hace a su propio riesgo. Debe aprender sobre las prácticas y políticas de privacidad y seguridad de sitios de Internet externos antes de proporcionarles sus datos personales.</PoliticsText>
      <PoliticsSubTitle>Como examinar, actualizar o borrar la información de registro</PoliticsSubTitle>
      <PoliticsText>Como parte del uso de nuestros servicios, usted es responsable de actualizar la información sometida para que sea actualizada y completa. Para actualizar su información de registro, por favor acceda a su cuenta de Escuela Americana de Innovación S.A.C. y haga el cambio deseado en modificar perfil. Usted también podrá acceder su cuenta de Escuela Americana de Innovación S.A.C. para cambiar sus preferencias tales como cancelar su suscripción a la lista de correos electrónicos.</PoliticsText>
    </ContainerPolitics>
  )
}

export default Politics